# Generated by Django 3.1.5 on 2021-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renttoys', '0002_auto_20210208_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='cost1day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
