# Generated by Django 3.1.5 on 2021-02-11 06:55

from django.db import migrations, models
import renttoys.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('renttoys', '0003_toy_cost1day'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='image',
            field=models.ImageField(blank=True, upload_to=renttoys.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
