# Generated by Django 3.1.6 on 2021-02-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renttoys', '0004_toy_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
